### PR TITLE
Use organization id on login

### LINKED ISSUE #217: Use organization ID instead of name as unique key
Actuellement, le nom est utilisé comme username d'organization.

### PR DESCRIPTION
**Pull request by vincentchalamon**
Fix #217

### CODE REVIEW

**Comment by mRoca** [comment]
The organization name is currently used as `@ORM\UniqueConstraint(name="organisation_name_unique", columns={"name"})`. What do you think about removing this constraint in this PR?

The unique name constraint was useful only while we had a single parent organization, it's not relevant anymore. You can remove the constraint in you PR or we could do it in another one, wdytat ?

**Comment by vincentchalamon** [comment]
There is still an order by name in the `OrganizationRepository::findByIdOrParentIdQueryBuilder`, called from `UserType::buildForm`. I would keep this index on the name property to boost this order by. WDYT @mRoca ?

**Comment by mRoca** [comment]
There are currently 2 indexes on the name (don't ask why, I dunno :-) ), you can remove the UniqueConstraint and keep the basic index:

```
 * @ORM\Table(
 *   uniqueConstraints={
 *     @ORM\UniqueConstraint(name="organisation_name_unique", columns={"name"})
 *   }, indexes={
 *     @ORM\Index(name="organization_name_idx", columns={"name"}),
 *   }
 * )
```

**Comment by mRoca** [comment]
And don't forget the related doctrine migration ;-)

**Pull request merged**
